### ISSUE TITLE
Incorrect S3 Link when deploying to us-east-1

### ISSUE THREAD

**Issue by schuettc** [widdix/mastodon-on-aws#10] opened 2022-11-21 21:51 UTC
Looks like avatars, etc. are not using the correct URL.  

This is the URL generated by the server: https://s3-us-east-1.amazonaws.com/mastodon-on-aws-bucket-870xpa8cwey1-bucket-af70sek4pfly/cache/accounts/avatars/109/383/759/229/326/700/original/0f056e8c0194defd.png

However, this is the actual url: https://mastodon-on-aws-bucket-870xpa8cwey1-bucket-af70sek4pfly.s3.amazonaws.com/cache/accounts/avatars/109/383/759/229/326/700/original/0f056e8c0194defd.png

**Comment by schuettc** [comment] 2022-11-21 22:59
Fixed:

Updated task definition.  However, I suspect that this will not work correctly in all regions but haven't tested.  I am using us-east-1 and thought there was a different in S3 URLs there.  

```json
      "environment": [
        {
          "name": "S3_BUCKET",
          "value": "mastodon-on-aws-bucket-870xpa8cwey1-bucket-af70sek4pfly"
        },
        {
          "name": "S3_ENABLED",
          "value": "true"
        },
        {
          "name": "S3_ENDPOINT",
          "value": "https://mastodon-on-aws-bucket-870xpa8cwey1-bucket-af70sek4pfly.s3.amazonaws.com"
        },
        {
          "name": "S3_HOSTNAME",
          "value": "s3.amazonaws.com"
        },
        {
          "name": "S3_OVERRIDE_PATH_STYLE",
          "value": "false"
        },
        {
          "name": "S3_PROTOCOL",
          "value": "https"
        },
        {
          "name": "S3_REGION",
          "value": "us-east-1"
        },
      ],
```

**Comment by schuettc** [comment] 2022-11-22 02:11
Seems like something still broken with S3 when uploading Avatar/Header, etc.  Will keep poking at it.

**Comment by schuettc** [comment] 2022-11-22 03:17
Local Images working now

```json
"environment": [
        {
          "name": "S3_BUCKET",
          "value": "mastodon-on-aws-bucket-870xpa8cwey1-bucket-af70sek4pfly"
        },
        {
          "name": "S3_ENABLED",
          "value": "true"
        },
        {
          "name": "S3_ENDPOINT",
          "value": "https://s3.amazonaws.com"
        },
        {
          "name": "S3_HOSTNAME",
          "value": "s3.amazonaws.com"
        },
        {
          "name": "S3_OVERRIDE_PATH_STYLE",
          "value": "false"
        },
        {
          "name": "S3_PROTOCOL",
          "value": "https"
        },
        {
          "name": "S3_REGION",
          "value": "us-east-1"
        },
      ],
```

**Comment by andreaswittig** [comment] 2022-11-22 07:22
I'm trying to understand, why this does not work for you with the default configuration. It works for me. Which AWS region are you using, @schuettc?

**Comment by jbold** [comment] 2022-11-22 07:30
> I am using us-east-1

@andreaswittig ⏫

**Comment by compuguy** [comment] 2022-11-25 02:46
@andreaswittig Apparently the https://s3-$(REGION).amazonaws.com doesn't work in us-east-1. Hit this same exact problem early on @schuettc. Looks like you found a way around it. Now it just needs to be somehow included into the CloudFormation template.

**Comment by annatech** [comment] 2022-12-11 18:18
I can confirm the same issue as @schuettc. 

To work around it I tried implementing this traffic flow... to no avail. 

Route 53 > CloudFront > S3 (web app passthrough) > ALB

I also tried:

Route 53 > CloudFront > ALB

... and a few other iterations in configuration. 

My goal there was to leverage a Lamba Edge function on the CloudFront distribution to fix the broken S3 bucket URL. 

Anyway, that did not work. 

Will wait for a permanent fix to the CloudFormation template. 

Overall solid work, @andreaswittig !

**Comment by compuguy** [comment] 2022-12-11 23:12
I made the following tweaks int he AppEnvironment key and values in order to get it to use the correct domain in us-east-1: https://github.com/compuguy/mastodon-on-aws/blob/istoleyourpw-deploy/mastodon.yaml#L286
Its essentially this change:
```
        AppEnvironment4Key: 'S3_HOSTNAME'
        AppEnvironment4Value: !Sub 's3.${AWS::Region}.amazonaws.com'
```

**Comment by JohnCido** [comment] 2023-01-04 15:19
The exact same issue happened on my us-east-1 stack.
This is the correct URL:
`https://[bucket-name].s3.amazonaws.com/site_uploads/files/000/000/002/@1x/[image].png`
And this is the URL used on the page:
`https://s3-us-east-1.amazonaws.com/[bucket-name]/site_uploads/files/000/000/002/@1x/[image].png`

**Comment by andreaswittig** [comment] 2023-02-13 19:29
I've added CloudFront to distribute the assets stored on S3. Could someone please check, wether the latest version (`v0.11.0`) is running fine in `us-east-1`?

**Comment by compuguy** [comment] 2023-07-13 16:22
I think this has been fixed with the move to CloudFront @schuettc @andreaswittig. I've not had any issues with this S3 link issue since v0.11.0. This can be closed.

**Comment by andreaswittig** [comment] 2023-07-13 18:00
@compuguy Thanks!

**Closed as completed** 2023-07-13 18:00 UTC
Labels: bug
